### PR TITLE
Fix issues with `using` being added erroneously

### LINKED ISSUE #30: `GivenAndUsing` rule duplicates `using` keyword when explicitly passing a `using` param
Thank you for these rules, it makes the migration to new Scala 3 syntax a lot simpler!

I've found that the `GivenAndUsing` rule can produce invalid syntax when existing code is already passing a `using` param explicitly.

For example given this code:

```scala
def test(using i: Int): Int = i

test(using 1)
```

The `GivenAndUsing` rule rewrites it to this:

```scala
def test(using i: Int): Int = i

// Note duplicated `using` keyword here
test(using using 1)
```

I'm guessing something around [here](https://github.com/arktekk/scala3-scalafix/blob/main/rules/src/main/scala/fix/GivenAndUsing.scala#L53-L54) needs to check whether there's already a `using` keyword?

### PR DESCRIPTION
**Pull request by mrdziuban**
Fixes #30 

It turned out this was only an issue on later scalafix/scalameta versions, so I had to upgrade dependencies to actually reproduce and fix it.

The commit with the actual fix is https://github.com/mrdziuban/scala3-scalafix/commit/c6be4680ca1634f060fb012f1dd7faf083517421.

The other changes were to address things related to the scalafix upgrade:

- Resolve deprecation warnings
- Use `templ.body.children` in the `SemiAuto` rule instead of just `templ.children`
  - In the old scalafix version, `templ.children` returned all the statements within the template, but now it just returns a `List` with one element -- the template's body -- so we need to look at the children of the body

EDIT:

This also fixes an issue where `using` is added to code that's calling a function returned by a method that takes `using` parameters. See example code in https://github.com/arktekk/scala3-scalafix/pull/31#issuecomment-2397854150

### CODE REVIEW

**Review by hamnis — APPROVED** [review]
Nice!
Looks good to me, leaving merging to @ingarabr

**Comment by mrdziuban** [comment]
There's one more bug I'm going to try to address here, where the `using` keyword is incorrectly added when calling a function returned by a method with `using` parameters.

For example, this code:

```scala
def test(using i: Int): String => String = s => s

given i: Int = 1
test("")
```

is rewritten to:

```scala
def test(using i: Int): String => String = s => s

given i: Int = 1
// Note the `using` keyword is added here but results in a compile error
test(using "")
```

**Comment by mrdziuban** [comment]
Fixed that bug and updated the PR title and description to match

**Comment by ingarabr** [comment]
Looks good to me. Thank you for updating dependencies and deprecated code. Much appreciated :)

**Pull request merged**
